-- --- ÖDEV GÖREVLERİ ---

-- 1. GÖREV: Fiyatı 50 TL ile 150 TL arasında olan tüm ürünleri listeleyin.
-- ...

-- 2. GÖREV: "Temizlik" kategorisindeki (id=4) tüm ürünlerin fiyatını %20 düşürün (fiyat * 0.80).
-- ...

-- 3. GÖREV: İsminin içinde "Kurusu" geçen tüm ürünleri bulun ve onları sistemden silin.
-- ...

-- 4. GÖREV: Ürün ID'si 1 olan ürünün stoğuna 200 adet ekleyin.
-- ...
